### PR TITLE
fix wrong locale order in checkin page

### LINKED ISSUE #341: wrong locale order in checkin page
> Reported by Kira

Problem is **recover** (in bold) should go after the exclamation mark. 

Checkin page before having locales: 

https://github.com/railslove/rcvr-app/blob/638a7c3258ac58dc7220bc7e49346bb052214382/pages/checkin.tsx#L205-L223

This bug couldn't be found before since couldn't test the `checkin`  page locally till recently (see #331 )

### PR DESCRIPTION
**Pull request by stringparser**
Closes #341.

This was clearly due to trying to keep the boldface for `recover`.

Here commit before having locales:

- https://github.com/railslove/rcvr-app/blob/638a7c3258ac58dc7220bc7e49346bb052214382/pages/checkin.tsx#L205-L223

### CODE REVIEW

File: pages/checkin.tsx [hunk 1]
```diff
@@ -216,9 +216,8 @@ export default function CheckinPage() {
             <p>{t('introText')}</p>
             <p>{t('address')}</p>
             <p>
-              {isRcvrEnv ? <b>recover</b> : null}
-              {isRcvrEnv ? ' ' : null}
-              {t('dataProtection')}
+              {t('dataProtection1')}
+              {isRcvrEnv ? <b>recover</b> : null} {t('dataProtection2')}
```
Comment (bitboxer) [inline pages/checkin.tsx:220]: would it be possible to move the recover into the translation text? Reads weird this way.

Comment (stringparser) [reply pages/checkin.tsx:220]: Not without converting that file to `.tsx` which then would make it a page. I can split the translation key for the second part to have it with recover so the logic is visible here instead of in that translation file. Give me a sec.

Comment (stringparser) [reply pages/checkin.tsx]: done

**Review by bitboxer — APPROVED** [review]
